name: Lint HTML and JavaScript

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    
    - name: Install HTMLHint
      run: npm install htmlhint

    - name: Run HTMLHint
      run: npx htmlhint "**/*.html"

    
    - name: Install ESLint
      run: npm install eslint

    - name: Run ESLint
      run: npx eslint "**/*.js"

