name: Lint HTML and JavaScript

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install HTMLHint
      run: npm install htmlhint

    - name: Run HTMLHint
      run: npx htmlhint "**/*.html"

    - name: Install ESLint and Compatibility
      run: |
        npm install eslint @eslint/eslintrc

    - name: Run ESLint
      run: npx eslint "**/*.js"
# to deploy to pages
  deploy: 
    runs-on: ubuntu-latest
    needs: lint  
    if: ${{ github.ref == 'refs/heads/main' }}  

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./


